Link pthread into phosg by default
Using g++-9 on Ubuntu 16.04, I got errors of the form

```
[ 34%] Linking CXX executable jsonformat
libphosg.a(Process.cc.o): In function `maybe_add_atfork_handler()':
/tmp/tmpibvp6fnb/phosg/src/Process.cc:210: undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
```

Online discussion says `pthread_atfork` is sometimes part of libc instead of pthreads. I'm not sure what the exact conditions are, but linking in pthreads explicitly seems safer.

phosg builds for me with this line on both Ubuntu 16.04 and 20.04.